# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Com Tam To Go
description: > # this means to ignore newlines until "baseurl:"
  All things David.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github_username: David-Wolgemuth
social-icon:
 -title: github_username
  url: https://github.com/David-Wolgemuth
  class: github
 -title: Twitter
  url: https://twitter.com/xoaichien
  class: twitter

# Build settings
markdown: kramdown
gems:
 - jekyll-gist