title: David Wolgemuth
email: davidjwolgemuth@gmail.com
description: >-
  Discussion of all things relating to code.  I'm a big fan of Ruby,
  JavaScript, and Swift.  Also a fan of algorithms.
baseurl: ""
url: "david-wolgemuth.github.io"
github_username:  david-wolgemuth
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
